version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.1

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"

    steps:
      - checkout
      - run: make clean build
